version: '3'
services:
  web:
    container_name: "ss4"
    build:
      context: .
    working_dir: /var/www
    volumes:
      - .:/var/www/html
    ports:
      - "80:80/tcp"
    command: "php composer.phar update"

  database:
    container_name: "mysql5.7"
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306/tcp"

volumes:
  db-data: